flowchart TD
    A1[Israelite-Judean Polytheism and Yahwism]
    A1 --> A2[Babylonian Exile Yahwism]
    A2 --> A3[Second Temple Period Early Judaism] 
    A2 --> A4[Second Temple Period Early Judaism Samaritanism]

    A3 --> B1[Early Judaism]
    A4 --> B2[Early Samaritanism]

    B1 --> C1[Mishnaic Judaism]
    B1 & B2 --> C2[Yeshua'ite Judaism]

    C1 --> D1[Modern Judaism]
    B2 --> D2[Modern Samaritanism]
    
    C2 --> XX1[Jewish Christianity]
    XX1 --> XX2[Greco-Roman Christianity]
    XX2 --> XX3[Modern Christianity]

    XX3 --> C2 & XX1
