flowchart TD
    A1[Israelite-Judean Polytheism and Yahwism]
    A1 --> A2[Babylonian Exile Yahwism]
    A2 --> A3[Second Temple Period Yahwite Judaism] 
    A2 --> A4[Second Temple Period Yahwite Samaritanism]

    A3 & A4 --> B1[Early mainstream Judaism]
    A3 & A4 --> B2[Early mainstream Samaritanism]
    A3 & A4 --> B3[Early Yeshua'ite Judaism]

    B1 --> C1[Judaism]
    B2 --> C2[Samaritanism]
    B3 --> C3[Christianity]

    
