flowchart TD

  A1[Very Phonetically Consonant] --> B1[Very Non Tonal]
  A2[Very Phonetically Mixed] --> B2[Very Tonally Mixed]
  A3[Very Phoneicallly Vowelant] --> B3[Very Much Tonal]

  A1 & B3 --> C1[Easier to Learn]
  B3 & A1 --> C2[Harder to Learn]
