flowchart TD
    A1[Ancient Torah Parts]
    A1 --> A2[First Temple Torah]
    A2 --> A3[First Temple Nebiim] 
    A2 --> A4[First Temple Ketubim]
    A2 --> A5[First Temple Apocrypha]
    A2 & A3 & A4 & A5 --> B1[Second Temple Scrolls]

    B1 --> B2[Second Temple Torah Versions]
    B1 --> B3[Second Temple Nebiim]
    B1 --> B4[Second Temple Ketubim]
    B1 --> B5[Second Temple Apocrypha]

    B2 & B3 & B4 & B5 --> C1[Hebrew Bible]
    B2 & B3 & B4 & B5 --> C2[Essene Literature]
    B2 & B3 & B4 & B5 --> C3[Non Essene and Non Yesuha'ite Traditions]
    B2 & B3 & B4 & B5 --> C4[Yeshua'ite Oral Traditions]

    C1 & C3 --> D1[Jewish Literature]
    C1 & C3 --> D2[Mandean Literature]
    B2 && B3 && B4 && B5 & C2 & C4 --> D3[Early Christian Literature]

    D3 --> E1[New Testament]
