flowchart TD
    A1[Ancient Torah Parts]
    A1 --> A2[First Temple Torah]
    A2 --> A3[First Temple Nebiim] 
    A2 --> A4[First Temple Ketubim]
    A2 --> A5[First Temple Apocrypha]
    A2 & A3 & A4 & A5 --> B1[Second Temple Scrolls]

    B1 --> B2[Second Temple Torah Versions]
    B1 --> B3[Second Temple Nebiim]
    B1 --> B4[Second Temple Ketubim]
    B1 --> B5[Second Temple Apocrypha]

    B2 & B3 & B4 & B5 --> C1[Essene Traditions]
    B2 & B3 & B4 & B5 --> C2[Non Essene and Non Yesuha'ite Traditions]
    B2 & B3 & B4 & B5 --> C3[Yeshua'ite Traditions]

    

    
    A2 --> A[Post-TNK apocrypha]
    A1 & A2 --> 5[Yeshua'ite Writings]
    5 & A4 --> A5[]
    5 --> 6[Babylonian Monotheist Yahwism]
    6 --> 7[Judean Yahwism] & 8[Samaritan Yahwism]
    8 --> 9[Samaritan religion]
    X[Mesopotamian Paganism] --> 11
    7 --> 10[Saducee Judaism] & 11[Pharisaic Judaism] & 12[Essene Judaism] & 14[Fourth Philosophy]
    XX[Zoroastrian Gnostic Religion]
    12 & XX --> B[Mandean religion]
    11 & 12 & 9 --> 13[Yeshuaite Judaism]
    11 & XX --> 15[Rabbanite Judaism]
    10 & 15 --> 16[Karaite Judaism]
