flowchart TD

    %% Territorial group
    subgraph A[Territorial group]
        B1[Family]
        B2[Tribe]
        B3[Folk]
        B4[Nation]
    end

    B1 --> B2
    B2 --> B3
    B3 --> B4

    A --> B1
    A --> B2
    A --> B3
    A --> B4

    %% State
    subgraph C[State]
        C1[Uniethnic state]
        C2[Multiethnic state]
    end

    B3 --> C1
    B4 --> C2
