flowchart TD

    %% Territorial group
    subgraph A[Territorial group]
    end

    A --> B1[Family]
    A --> B2[Tribe]
    A --> B3[Folk]
    A --> B4[Nation]

    %% State
    subgraph C[State]
    C --> C1[Uniethnic state]
    C --> C2[Multiethnic state]
    end

    B3 --> C1
    B4 --> C2
